### ISSUE TITLE
local to buffer

### ISSUE THREAD

**Issue by dusans** [mhinz/vim-hugefile#1]
Is it possible to have the settings for huge files apply only to those buffers that have huge files open.

Cuz if i open a huge file and then a normal file (new tab/split) the normal file doesn't have syntax highlighting.

**Comment by mhinz** [comment]
Hmm, it should work only for huge files already.

```
$ vim hugefile
:e ~/.vim/vimrc
```

This works good for me, even when I switch between these buffers, or open them in a new split/tab.

Please give me an exact line that I can reproduce.

**Comment by dusans** [comment]
For the record. I use gvim (windows 7 64bit)

If i do a fresh restart of gvim the syntax now works on the other split buffer (small). But it cant move the cursor between split buffers. 

It may be a environmental issue with other plugins. Have to test it more.

try:

> $ vim hugefile
> :vsplit ~/.vim/vimrc
