### ISSUE TITLE
Does not work with "vimdiff": opens first file in splits only

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-hugefile#2]
When calling `vimdiff hugefile1 hugefile2`, only `hugefile1` gets opened in the split.
When trying to quit Vim, it tells about an additional file being opened ("one more file to edit"; which is not displayed).

This can be reproduced using:

```
vimdiff -Nu <(cat << EOF
filetype off
set rtp+=~/.vim/neobundles/hugefile 
filetype plugin indent on
syntax enable
EOF) /tmp/1a /tmp/1b
```

This works with the LargeFile plugin.

Skipping the setup for `&diff` might work, but LargeFile seems to handle it differently, and skipping all options for huge files is not a good solution probably.

**Comment by mhinz** [comment]
I'm mostly using Emacs lately, so.. would you mind maintaining or taking over this plugin?

**Comment by blueyed** [comment]
> I'm mostly using Emacs lately

Oh.

> would you mind maintaining or taking over this plugin?

Not currently. LargeFile works good for me, and I was just trying vim-hugefile because of some issue I could fix now.

**Comment by mhinz** [comment]
Okidoki, I'll change the README then, saying that I'm looking for a new maintainer. Unfortunately I don't have much time at the moment, so I'll try to concentrate on startify and signify.
