### ISSUE TITLE
Suggestion: syn sync clear

### ISSUE THREAD

**Issue by sfinktah** [mhinz/vim-hugefile#3]
`:syn sync clear`

If you can find a way execute that command, or otherwise disable syntax sync, then you can still keep your colored syntax with huge files.  As-is, (unsurprisingly) most syntax files will slow you down all to hell, which is why I assume they are disabled.

Not sure how you could actually achieve this ability automatically though, since some (all?) syntax files load via AutoBuffer plugins, eg:

```
au BufRead,BufNewFile *.{lst}   set filetype=cmix
```

And I don't know how you could intercept or set your own command to run **after**.   That why I haven't offered a pull request.

If you want to see that syntax highlight can work on huge files, try `:set syntax=asm` (fast) with `:set syntax=nasm` (slow) on a large file.  

I'm editing a 11,402,164 line IDAPro .lst (assembler) file right now with no lag and color highlighting.   The syntax file sourced the ".c" syntax, so it would normally be impossible to use.

**Comment by mhinz** [comment]
Hi. Sorry, but as the README states, this is not maintained anymore since I haven't used this plugin myself for years.

Feel free to fork it. :)

**Comment by sfinktah** [comment]
Oh, didn't notice, my bad.  Well, it still works pretty awesome, and I'll assume based on your amusing comments on LargeFile's code, that I could do with a worse platform to learn on.

OTOH, if you use YouCompleteMe and UltiSnips, you'll be aware of the difficulty in getting them to co-operated correctly together (despite a million assurances and examples of code showing how it can be done).  IIRC it fell down to having to have code run after everything was loaded, which was achieved with an AutoBuffer or similar event, a solution that I always thought kinda sucked.

Would be curious (if you do use these plugins) what your solution was.

A javascript like `setTimeout()` would do wonders for such problems as these.

**Comment by sfinktah** [comment]
Oh, and if I may ask another VIM question...

I have read so very many guides on profiling vim, and none of them actually helped me for shit.

The reason I ended up here, was that sometimes when a huge file was opening and I hit ^C it would spout an error that it had been interrupted during something to do with MatchParen (if you looked into it hard enough).

You can analyse all the loading times you like, but nothing I've found actually exposes the time taken up by (and I'm pasting from matchparen.vim here)

```
  autocmd! CursorMoved,CursorMovedI,WinEnter * call s:Highlight_Matching_Pair()
  if exists('##TextChanged')
    autocmd! TextChanged,TextChangedI * call s:Highlight_Matching_Pair()
  endif
```

Assumededly because the execution time isn't realised during script loading.

None of the `--cmd profile *` options seemed to show it, `vim -V` didn't, and of course `vim --startuptime` wasn't much help either.  Do you have a secret profiling method you used when developing HugeFile?
