### ISSUE TITLE
vim 8.0 patch 1-134 incompatibility with *MatchParen

### ISSUE THREAD

**Issue by systemmonkey42** [mhinz/vim-hugefile#4]
The hugefile autocmd for **BufReadPre**  causes an "

> **E201**" *ReadPre cannot modify buffer

(possiblly) due to changes in matchparen.vim.

Removing the calls to No/DoMatchParen resolves the issue.

This isn't always seen, but is a huge issue (pun intended) when selecting a "huge" file from a quickfix window.

Also, the autoload functions dont pass vint cleanly.

**Comment by mhinz** [comment]
Hi, as the README states, I don't maintain this plugin anymore. Please feel free to fork it.
