### ISSUE TITLE
textwidth and nowrap

### ISSUE THREAD

**Issue by bounceme** [mhinz/vim-hugefile#5]
this is mainly for giant lines. the textwidth at anything other than 0 will cause vim to calculate where to split on every insertion. wrapping can also help speed up the display.

**Comment by mhinz** [comment]
Please see the README, I don't maintain (because I don't use it myself) anymore.

Feel free to fork it or, if you want, I grant you commit rights for this one.

Thanks anyway!

**Comment by bounceme** [comment]
that's alright, if this is a stable project, forking is a good solution for these kind of things
